### PR TITLE
#10 - Fix: vulnerability fixed

### PR DESCRIPTION
**Pull request by jkrajinovic**
**Required**
`npm install`

closes: #10

### CODE REVIEW

**Comment by zrajic** [comment]
@jkrajinovic why is adding `ws` package to project fix to vulnerability? Svelte template app is not using it...can you explain it little bit more?

**Comment by jkrajinovic** [comment]
Actually great question.
For a second I though it is not needed.

But in package.lock some other module is using ws package.

https://github.com/jkrajinovic/dms/blob/e966cb6229fdc82edd435fb864f3a1148dbb3a2c/package-lock.json#L2586

That caused github to bring vulnerability issue and to fix it I needed to update
the package witch in end landed in package json. I gues to override some other package dependency.

Great catch

**Comment by zrajic** [comment]
@jkrajinovic is that what we really wanna do. It could be tricky because version that you added is 7.2.0 or higher and dependency requires 1.1.15. Correct me if i am wrong but isn't best practice not to add higher packages version because something could not be compatible with that version?

**Comment by jkrajinovic** [comment]
Sure. Right now everything is working. Let's be optimistic.
Because security and fixed bugs I think its best practice to use he latest version of packages, and if
something brakes we'll downgrade. If you have better version that suits our needs please suggest.
I'll rather fix compactibility than risk your data been extracted and used on good forbid some porn sites.

**Pull request merged**
